namespace: "netapp"
name: "ontap"
version: "23.4.0"
authors:
    - "NetApp Ansible Team <ng-ansible-team@netapp.com>"
readme: README.md
license_file: COPYING
description: NetApp ONTAP Collection
repository: https://github.com/ansible-collections/netapp.ontap
issues: https://github.com/ansible-collections/netapp.ontap/issues
homepage: https://netapp.io/configuration-management-and-automation/
tags:
    - storage
    - ontap
    - netapp
