---
# defaults file for na_ontap_nas_create
na_ontap_nas_create_netapp_hostname:
na_ontap_nas_create_netapp_password:
na_ontap_nas_create_netapp_username:
na_ontap_nas_create_validate_certs: false
na_ontap_nas_create_nas:
